import Image from "next/image";import Link from "next/link";import {notFound} from "next/navigation";
const data={
 "tv-units":{title:"TV units\nbuilt into the room.",copy:"Custom media walls and TV units designed around storage, lighting, display and the proportions of the room.",image:"/projects/tv-units/illuminated-media-wall-01.jpeg",alt:"Custom illuminated media wall",items:["Floating cabinetry","Feature panelling","Integrated display shelving","LED accent lighting","Wall-mounted layouts","Fitted storage"],gallery:["/projects/tv-units/illuminated-media-wall-03.jpeg","/projects/tv-units/minimal-media-wall-02.jpeg","/projects/tv-units/feature-wall-04.jpeg"]},
 "kitchens":{title:"Kitchens that\nwork beautifully.",copy:"Custom kitchen cabinetry planned around storage, movement and everyday use. Contact us to discuss the room and the finish you have in mind.",image:"/inspiration/warm-kitchen-reference.jpg",alt:"Warm neutral kitchen visual reference",reference:true,items:["Cabinet layout","Practical storage","Finish selection","Integrated lighting"],gallery:["/inspiration/warm-kitchen-reference.jpg","/projects/tv-units/illuminated-media-wall-03.jpeg","/projects/furniture/bedside-cabinets-workshop-01.jpeg"]},
 "bic-cupboards":{title:"Storage,\nbuilt in.",copy:"Fitted cupboards developed around the available room, your storage needs and the finish of the wider interior.",image:"/inspiration/illuminated-wardrobe-reference.jpg",alt:"Illuminated fitted wardrobe visual reference",reference:true,items:["Custom sizing","Internal shelving","Hanging space","Drawers","Finish selection"],gallery:["/inspiration/illuminated-wardrobe-reference.jpg","/projects/bedrooms/panelled-bedroom-01.jpeg","/projects/tv-units/feature-wall-04.jpeg"]},
 "ceilings":{title:"Light shapes\nthe room.",copy:"Ceiling details that bring recessed light, bulkheads and warm LED accents into the architectural rhythm of a space.",image:"/projects/ceilings/recessed-lighting-01.jpeg",alt:"Recessed ceiling with warm LED accent lighting",items:["Recessed lighting","Bulkhead details","LED accents","Feature ceilings"],gallery:["/projects/ceilings/recessed-lighting-01.jpeg","/inspiration/sculptural-ceiling-reference.jpg","/projects/tv-units/minimal-media-wall-02.jpeg"]}
} as const;
export function generateStaticParams(){return Object.keys(data).map(service=>({service}))}
export default async function Service({params}:{params:Promise<{service:string}>}){const{service}=await params;const d=data[service as keyof typeof data];if(!d)notFound();return <>
 <section className="service-canvas"><div className="service-canvas-media"><Image src={d.image} alt={d.alt} fill priority sizes="62vw"/><div className="service-canvas-index">{service==="tv-units"?"01":service==="kitchens"?"02":service==="bic-cupboards"?"03":"04"}</div>{"reference" in d&&d.reference&&<span>Visual reference · Pinterest</span>}</div><div className="service-canvas-copy"><small>Interior Works Co. · Service</small><h1>{d.title.split("\n").map((x,i)=><span key={x}>{x}{i===0&&<br/>}</span>)}</h1><p>{d.copy}</p><Link className="button" href="/contact">Request a quote <b>↗</b></Link></div></section>
 <section className="service-anatomy"><div className="anatomy-heading reveal"><small>What the room needs</small><h2>Function first.<br/><em>Finish everywhere.</em></h2><p>{d.copy}</p></div><div className="anatomy-list">{d.items.map((x,i)=><div className="reveal" key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></section>
 <section className="service-gallery"><div className="sg-lead reveal"><Image src={d.gallery[0]} alt={`${d.title.replace("\n"," ")} ${"reference" in d?"visual reference":"detail"}`} fill sizes="55vw"/></div><div className="sg-side"><figure className="reveal"><Image src={d.gallery[1]} alt="Interior detail" fill sizes="40vw"/></figure><figure className="reveal"><Image src={d.gallery[2]} alt="Fitted furniture and finish detail" fill sizes="40vw"/></figure></div></section>
 <section className="service-close"><small>A space should work before it impresses.</small><h2>Built around the room.<br/><em>Finished around you.</em></h2><Link className="button" href="/contact">Start this kind of project <b>↗</b></Link></section>
 </>}
