import Image from "next/image";import Link from "next/link";import {projects} from "@/lib/site-data";import {RoomExplorer} from "@/components/room-explorer";
export default function Home(){return <>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">Interior design · Custom furniture · Harare</span><h1>Interiors made<br/>for the way<br/><em>you live.</em></h1><p>Interior Works Co. creates custom interiors, fitted furniture and practical living spaces for homes in Harare.</p><div className="actions"><Link className="button" href="/projects">View our projects <b>↗</b></Link><Link className="text-link" href="/contact">Request a quote ↗</Link></div><small className="hero-services">TV Units · Kitchens · BICs · Ceilings · Custom Furniture</small></div><div className="hero-image"><Image src="/projects/tv-units/illuminated-media-wall-03.jpeg" alt="Illuminated fitted media wall by Interior Works Co." fill priority sizes="(max-width:800px) 100vw, 58vw"/><div className="image-note"><span>01</span> Fitted interiors<br/>made for home.</div></div><div className="scroll-cue">Scroll to explore <i/></div></section>
 <section className="intro reveal"><div><small>Interior Works Co.</small><h2>Designed with purpose.<br/><em>Built around home.</em></h2></div><div><p>Interior Works Co. designs and builds fitted interior solutions that bring storage, comfort and finish together.</p><p>From a clean TV wall to a complete kitchen, bedroom storage or custom piece of furniture, each project is developed around the room and how it will actually be used.</p></div></section>
 <RoomExplorer/>
 <section className="project-film"><div className="film-heading reveal"><small>Selected work · Real client photographs</small><h2>Spaces that feel<br/><em>resolved.</em></h2><p>Not decoration added at the end. Each wall, storage volume and light source works as part of one interior.</p></div><div className="film-grid">{projects.slice(0,6).map((p,i)=><Link href={`/projects/${p.slug}`} className={`film-frame f${i+1} reveal`} key={p.slug}><Image src={p.image} alt={p.alt} fill sizes="(max-width:700px) 100vw, 50vw"/><div><small>{p.category}</small><h3>{p.title}</h3><span>View project ↗</span></div></Link>)}</div><Link className="button" href="/projects">See the complete portfolio <b>↗</b></Link></section>
 <section className="light-story"><div className="light-copy reveal"><small>The Interior Works signature</small><h2>Light is not<br/><em>an afterthought.</em></h2><p>The supplied work uses illumination to give cabinetry depth, soften edges and turn storage into atmosphere.</p><div className="light-notes"><span>01<i/>Ambient glow</span><span>02<i/>Display light</span><span>03<i/>Architectural depth</span></div></div><div className="light-scenes"><figure className="scene-a"><Image src="/projects/tv-units/illuminated-media-wall-01.jpeg" alt="Warm LED illumination around a custom media wall" fill sizes="42vw"/></figure><figure className="scene-b"><Image src="/projects/tv-units/minimal-media-wall-02.jpeg" alt="Pendant light and illuminated floating media unit" fill sizes="32vw"/></figure><span className="light-line"/></div></section>
 <section className="cinematic reveal"><Image src="/projects/bedrooms/panelled-bedroom-01.jpeg" alt="Finished bedroom with layered wall panelling and integrated lighting" fill sizes="100vw"/><h2>A quieter kind<br/>of <em>luxury.</em></h2><div className="cinematic-meta"><small>Bedroom interior</small><span>Panel detail · Integrated light · Calm material palette</span></div></section>
 <FurnitureStory/><Process/>
 <section className="about-preview reveal"><Image src="/projects/tv-units/illuminated-media-wall-01.jpeg" alt="Finished fitted interior by Interior Works Co." fill sizes="50vw"/><div><small>About the studio</small><h2>Interiors<br/><em>with intention.</em></h2><p>A Harare-based interior and furniture company creating fitted solutions that bring cabinetry, furniture, light and practical storage together.</p><p>The aim is simple: make the room feel considered, useful and complete.</p><Link className="text-link" href="/about">Meet Interior Works Co. ↗</Link></div></section>
 </>}
function FurnitureStory(){return <section className="furniture-story"><div className="furniture-word" aria-hidden="true">MADE</div><div className="furniture-copy reveal"><small>Custom furniture</small><h2>Made by hand.<br/><em>Made for the room.</em></h2><p>From upholstered beds to bedside cabinets and display furniture, every piece begins with a practical need and ends with a finish that belongs in the space.</p><Link className="button light" href="/furniture">Explore the collection <b>↗</b></Link></div><div className="furniture-triptych"><figure><Image src="/projects/furniture/bedside-cabinets-workshop-01.jpeg" alt="Custom bedside cabinets in the workshop" fill sizes="30vw"/><figcaption>01 · In the workshop</figcaption></figure><figure><Image src="/projects/furniture/upholstered-bed-01.jpeg" alt="Made-to-order upholstered bed" fill sizes="30vw"/><figcaption>02 · Built for rest</figcaption></figure><figure><Image src="/projects/furniture/console-and-mirror-01.jpeg" alt="Custom console and mirror set" fill sizes="30vw"/><figcaption>03 · A finished statement</figcaption></figure></div></section>}
function Process(){const steps=[["01","Tell us about the space","Send measurements, photographs or arrange a consultation."],["02","Design & plan","We develop the layout, finishes and practical requirements around the room."],["03","Build","Furniture and fitted elements are produced to the agreed design."],["04","Install","The final pieces are fitted and the room comes together."]];return <section className="process"><div className="section-title reveal"><small>From first message to finished room</small><h2>How we <em>work.</em></h2></div><div className="process-line">{steps.map(x=><article className="reveal" key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="process-gallery reveal"><Image src="/projects/furniture/bedside-cabinets-workshop-01.jpeg" alt="Furniture being completed in the workshop" width={900} height={650}/><div><small>Workshop</small><h3>The making is part<br/>of the story.</h3><p>Workshop imagery is shown as process—not falsely paired with an unrelated completed room.</p></div></div></section>}
