"use client";
import Image from "next/image";import Link from "next/link";import {useEffect,useState} from "react";import {usePathname} from "next/navigation";import {whatsapp} from "@/lib/site-data";
const nav=[["Home","/"],["Services","/services"],["Projects","/projects"],["Furniture","/furniture"],["About","/about"],["Contact","/contact"]];
export function SiteShell({children}:{children:React.ReactNode}){
 const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);const pathname=usePathname();
 useEffect(()=>{const f=()=>setScrolled(scrollY>24);f();addEventListener("scroll",f,{passive:true});return()=>removeEventListener("scroll",f)},[]);
 return <><div className="loader" aria-hidden="true"><Image src="/brand/interior-works-logo.png" alt="" width={150} height={130}/><i/></div>
 <header className={scrolled?"site-header scrolled":"site-header"}><Link href="/" className="brand" aria-label="Interior Works Co. home"><Image src="/brand/interior-works-logo.png" alt="Interior Works Co." width={118} height={96} priority/></Link><nav>{nav.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</nav><Link className="header-cta" href="/contact">Book a consultation</Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Open navigation"><span/><span/></button></header>
 <div className={open?"mobile-menu open":"mobile-menu"}>{nav.map(([n,h],i)=><Link key={h} onClick={()=>setOpen(false)} href={h}><small>0{i+1}</small>{n}</Link>)}<a href={whatsapp}>WhatsApp · +263 77 815 3441</a></div>
 <main>{children}</main>{(pathname==="/services"||pathname==="/services/kitchens"||pathname==="/services/bic-cupboards"||pathname==="/services/ceilings")&&<InspirationStrip/>}<FinalCTA/><Footer/><a className="whatsapp" href={whatsapp} target="_blank" aria-label="Chat with Interior Works Co. on WhatsApp">WA</a></>}
function InspirationStrip(){const refs=[
 ["/inspiration/warm-kitchen-reference.jpg","Kitchen atmosphere","https://www.pinterest.com/pin/2885187258475437/"],
 ["/inspiration/illuminated-wardrobe-reference.jpg","Wardrobe lighting","https://www.pinterest.com/pin/69946600458534159/"],
 ["/inspiration/sculptural-ceiling-reference.jpg","Ceiling form","https://www.pinterest.com/pin/323485185759574342/"]
];return <section className="inspiration"><div className="inspiration-copy reveal"><small>Design direction · Visual references</small><h2>A room is more than<br/><em>the furniture in it.</em></h2><p>We study how light, storage and architectural form can work together before the details are resolved for your own space.</p><span>Pinterest references shown for inspiration only—not Interior Works Co. projects.</span></div><div className="inspiration-stack">{refs.map(([src,label,href],i)=><a className={`inspo-card i${i+1}`} href={href} target="_blank" rel="noreferrer" key={src}><Image src={src} alt={`${label} visual reference`} fill sizes="(max-width:700px) 80vw, 28vw"/><b>{label}</b><small>Reference ↗</small></a>)}</div></section>}
function FinalCTA(){return <section className="final-cta"><div><small>Have a space in mind?</small><h2>Let&apos;s make it<br/><em>feel finished.</em></h2></div><div><p>From a single custom unit to a complete fitted interior, tell us what you&apos;re working on and we&apos;ll help shape the next step.</p><div className="actions"><Link className="button light" href="/contact">Request a consultation <b>↗</b></Link><a className="text-link light-text" href={whatsapp}>WhatsApp us ↗</a></div></div></section>}
function Footer(){return <footer><div className="footer-top"><div><Image src="/brand/interior-works-logo.png" alt="Interior Works Co." width={170} height={145}/><p>Custom interiors and fitted furniture<br/>for modern living.</p></div><div><small>Explore</small>{nav.slice(1).map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><small>Start a project</small><a href="tel:+263778153441">+263 77 815 3441</a><a href="mailto:interiorworksco@gmail.com">interiorworksco@gmail.com</a><span>Harare, Zimbabwe</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Interior Works Co.</span><a href="https://wa.me/263789937251" target="_blank">Website built &amp; developed by Jaeger Media</a></div></footer>}
